language: node_js

node_js:
  - "18"

install:
  - npm install

script:
  - npm test

before_deploy:
  - mkdir -p deploy
  - cp app.js discount.js package.json package-lock.json README.md deploy/

deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "szadam9806-lab4-psoir"
  local_dir: "deploy"
  upload-dir: "Szymanski"
  skip_cleanup: true
  on:
    branch: main
